name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        id: docker_login
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and optionally push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ steps.docker_login.outcome == 'success' }}
          tags: boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Export amd64 image as tar
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sdv-runtime-amd64.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Export arm64 image as tar
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output type=docker,dest=sdv-runtime-arm64.tar \
            -t boschvn/sdv-runtime:${{ steps.vars.outputs.VERSION }} .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image tars to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sdv-runtime-amd64.tar
            sdv-runtime-arm64.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}